version: '3.4'

services:
  resttest.dbservice:
    container_name: resttest.dbservice
    image: ${DOCKER_REGISTRY}resttest/dbservice
    build:
      context: .
      dockerfile: DbService/Dockerfile
