version: '3.4'

services:
  resttest.webapi:
    container_name: resttest.webapi
    image: ${DOCKER_REGISTRY}resttest-webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  resttest.webclient:
    image: ${DOCKER_REGISTRY-}resttest-webclient
    build:
      context: .
      dockerfile: WebClient/Dockerfile

