version: '3.4'

services:
  resttest.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44327
    ports:
      - "50532:80"
      - "44327:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - resttest.db
      - resttest.storage
    
  resttest.db:
    container_name: resttest.db
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "test_]7tLeW!'4K#2z3&!qhTzJaU8pX6wYv"
      ACCEPT_EULA: Y
      MSSQL_PID: Developer

  resttest.storage:
    container_name: resttest.storage
    image: arafato/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"